### ISSUE TITLE
出现不符合预期的参数设定

### ISSUE THREAD

**Issue by Taskschd** [xszqxszq/midi2exo#2]
操作一切正常，但是有时透明度设置为100或100以上，旋转设置大多不是0，xyz坐标也很多时候不是0，缩放率有时是0，而且每次将exo拖入窗口时的参数异常都不太相同
![Snipaste_2022-12-07_10-41-27](https://user-images.githubusercontent.com/117883953/206074792-b354adc0-b362-44f0-904c-bdd6a71366aa.png)
这些参数是exo默认生成的，没有经过更改
另外exo文件中的参数是没有问题的，这些问题是对1.17b的适配问题吗

**Comment by Taskschd** [comment]
我下载了汉化1.16d版本，确实没有出现上述问题，希望能增加对1.17b的适配

**Comment by xszqxszq** [comment]
1.17b已适配
